# Generated by Django 4.0.5 on 2022-06-19 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_book_isbn_alter_bookinstance_imprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_added',
            field=models.DateField(blank=True, help_text='Book added into the system.', null=True),
        ),
    ]
