# Generated by Django 4.0.5 on 2022-07-09 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_bookinstance_imprint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='barrower',
            new_name='borrower',
        ),
    ]
